facebook:
  client:
    clientId: ${FACEBOOK_CLIENT_ID}
    clientSecret: ${FACEBOOK_CLIENT_SECRET}
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
    
github:
  client:
    clientId: ${GITHUB_CLIENT_ID}
    clientSecret: ${GITHUB_CLIENT_SECRET}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
    
---
spring:
  profiles: default
  datasource:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  profiles: memoryDB
  datasource:
    url: jdbc:h2:mem:sampletest;MODE=MySQL  
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
