security:
  oauth2:
    client:
      clientId: 1126390864116179
      clientSecret: 43fae5bc8de09d15b79d21a902d8a72a
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
---
spring:
  profiles: default
  datasource:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  profiles: memoryDB
  datasource:
    url: jdbc:h2:mem:sampletest;MODE=MySQL  
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
